drop table visallo_systemnotifications;
drop table visallo_usernotifications;
drop table visallo_jettysession;
drop table visallo_artifactthumbnail;
drop table visallo_dictionaryEntry;
drop table visallo_vertex;
drop table visallo_edge;
drop table visallo_metadata;
drop table visallo_streaming_properties;